image: node:lts

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
