# Action
name: update-github-host

# Trigger
on:
  push:
    branches: [main]

  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

# Permissions
permissions:
  id-token: write
  contents: write
  pages: write

# Jobs
jobs:
  get-github-host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Building scripts
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy success
        run: echo https://dns-host.github.io/github/host.txt

  push-gitee-repo:
    runs-on: ubuntu-latest
    needs: get-github-host
    steps:
      - name: Add And Push Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          dst: gitee/dns-host
          src: github/dns-host
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_PERSONAL_TOKEN }}
          static_list: 'github'
          force_update: true
          account_type: org
